name: Upload

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        run: |
          mkdir artifact
          echo $GITHUB_SHA > artifact/sha
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: artifact
  upload-multiple:
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        run: |
          mkdir artifact1 artifact2
          echo $GITHUB_SHA > artifact1/sha1
          echo $GITHUB_SHA > artifact2/sha2
      - name: Upload first
        uses: actions/upload-artifact@v2
        with:
          name: Emoji-Pyramid
          path: artifact1

